version: "3"
name: "ohsome-cs-service"
services:
  api-service:
    build:
      dockerfile: Dockerfile
    command: "java -jar app.jar --spring.datasource.url=jdbc:clickhouse://localhost --server.servlet.context-path=/api"
    ports:
      - "127.0.0.1:8081:8080"