version: "3"
services:
  api-service:
    build:
      dockerfile: Dockerfile
    command: "java -jar app.jar --spring.datasource.url=jdbc:clickhouse://clickhouse-database"
    # ports are added in docker-compose.override.yml and docker-compose.integration.yml
    depends_on:
      - clickhouse-database

  clickhouse-database:
    build:
      context: database/
      dockerfile: Dockerfile
    volumes:
      - ch_data:/var/lib/clickhouse/
      - ch_logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"

volumes:
  ch_data:
  ch_logs: